title: "Safal Lama"
logo: "assets/initial-web/android-chrome-512x512.png"
description: "Nepali-Babu Jekyll Theme"
username: "loftyvirus"
actual_name: "nepalibabu-jekyll"
pronouns: "this/it"
baseurl: "/nepalibabu-nepali"
url: "https://loftyvirus.github.io"

# Social Media
social_links:
  - platform: github
    username: loftyvirus
    label: GitHub
    url: https://github.com/loftyvirus

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor


permalink: /posts/:title/
