name: Build and Deploy Jekyll Site

on:
  push:
    branches: [main] # or 'master' if that's your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1" # Match your local Ruby version
          bundler-cache: true

      - name: Generate category pages
        run: |
          mkdir -p ./categories
          ruby -e "
            require 'jekyll'
            
            site = Jekyll::Site.new(Jekyll.configuration({
              'source' => '.',
              'destination' => '_site'
            }))
            
            site.read
            dir = 'categories'
            
            site.categories.each_key do |category|
              category_dir = File.join(dir, category.downcase.gsub(' ', '-'))
              FileUtils.mkdir_p(category_dir)
              
              File.open(File.join(category_dir, 'index.html'), 'w') do |f|
                f.write(<<~HTML)
                  ---
                  layout: default
                  category: #{category}
                  ---
                  
                  <div class=\"cat-posts\">
                    <a href=\"#{site.baseurl}/categories/\" class=\"cat-back">← All categories</a>
                    <h2 class=\"cat-posts-title\">\"#{category}\"</h2>
                    <ul class=\"post-list\">
                      {% for post in site.categories.#{category} %}
                      <li class=\"post-item\">
                        <a href=\"#{site.baseurl}{{ post.url }}\" class=\"post-link\">
                          {{ post.title }}
                        </a>
                      </li>
                      {% endfor %}
                    </ul>
                  </div>
                HTML
              end
            end
          "

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
